name: My Pipeline
on: 
  workflow_dispatch:
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: setup java
             uses:actions/setup-java@v5.0.0
       With:
             java-version:"17"
